name: Steam Online Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,4 * * 0,6"
    - cron: "0 5 * * 1-5"
  push:
    branches:
      - main

jobs:
  MainWork:
    runs-on: ubuntu-latest
    steps:      
      - name: Clone Workflow Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.7'

      - name: Init
        run: |
          pip install beautifulsoup4
          echo "notification=true" >> $GITHUB_ENV
          echo "commit=false" >> $GITHUB_ENV

      - name: Run Checker
        run: python run.py ${{ secrets.STEAM_API_KEY }} ${{ secrets.STEAM_ID }}
          
      - name: Debugging
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "Test passed."
          
      - name: Send Notification
        if: env.notification == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: ${{ env.msg }}

      - name: Commit Files
        if: env.commit == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add history.txt
          git commit -m "Update on $(date +'%Y%m%d')"
          git push
